# Generated by Django 6.0.1 on 2026-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreAuthorizedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("MENTOR", "Mentor"),
                            ("FACULTY", "Faculty"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "assigned_class_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("roll_number", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
