# Generated by Django 6.0.1 on 2026-03-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_preauthorizeddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="preauthorizeddata",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("MENTOR", "Mentor"),
                    ("FACULTY", "Faculty"),
                    ("PARENT", "Parent"),
                ],
                max_length=10,
            ),
        ),
    ]
