# Generated by Django 6.0.1 on 2026-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="semester",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="semester",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.IntegerField(default=1),
        ),
    ]
